plugins {
    id("java-library")
    id("com.gradleup.shadow") version "8.3.11"
}

dependencies {
    api("io.github.archipelagomw:Java-Client:0.2.1") {
        exclude group: "com.google.code.gson"
        exclude group: "org.slf4j"
    }
}

tasks.shadowJar {
    relocate("org.java_websocket", "io.github.archipelagomw.shaded.org.java_websocket")
    relocate("org.apache.hc", "io.github.archipelagomw.shaded.org.apache.hc")
}
